### ISSUE TITLE
Did you find a fix?

### ISSUE THREAD

**Issue by gianlazz** [TomasMoskala/angular-apollo-app#2]
I think I'm experiencing the same behavior on my project. The app is able to make graphql calls in ios, the browser, though not in android.

**Comment by TomasMoskala** [comment]
I dont remember mate, I think it was
AndroidManifest.xml
android:usesCleartextTraffic="true"

**Comment by gianlazz** [comment]
Thank you this didn't end up being my issue though. It was related to a storage call that failed on the newer versions of android.
